# Generated by Django 4.2.1 on 2023-06-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_recipe_recipe_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_catagory',
            field=models.TextField(default='Uncategorized', max_length=300),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
