# Generated by Django 4.2.1 on 2023-06-04 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0003_recipe_recipe_catagory_alter_recipe_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_catagory',
            new_name='recipe_category',
        ),
    ]
