# Generated by Django 4.2.1 on 2023-06-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0005_recipe_recipe_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_category',
            field=models.TextField(default='Uncategorized', max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_description',
            field=models.TextField(max_length=100),
        ),
    ]
