# Generated by Django 4.2.1 on 2023-06-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_order_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item_price',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default='timezone.now'),
        ),
    ]
