# Generated by Django 4.2.1 on 2023-06-20 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0008_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
