# Generated by Django 4.2.1 on 2023-06-20 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_alter_user_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
