# Generated by Django 4.2.1 on 2023-06-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0011_order_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='recipe',
        ),
    ]
