# Generated by Django 4.2.1 on 2023-06-21 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0006_alter_recipe_recipe_category_and_more'),
        ('Customer', '0012_remove_order_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Food.recipe'),
        ),
    ]
